apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAYZV3wtIU3bmRHMVLnDOdssvWuqKqGmfMDgEJzmAgy9iBe9R6rcjjU4rhybFvedF5mcMJvlBsllH8fUWbLRoETe/EuVqN2YYvDGWbWdI5kfEk/Pox/ayRFS5GNnd48sxNbn+A/UcU4desLaSihUcSdyc0usQHe1/1XvexbuCmuQylYl7AyyMYluldkEhZMpg91g9cxCZb+csAgcrYWurTT8gjZ+VIzp4XgCwPuiPCrv+zCTb/goD+ZstpVmkdMwEV+DpSiy2vqEe47OsPA1PjjZ+poqqfbh+b/vThah/vifStqvNGA87NRFYt+B95WqSxBvIsp6FvHzs7VCUFoiMiXmq5aElYlpPno59+tT0/ENSXGupiAUfFeq/5vP+pNui01sjFORwnNLBIaV4r4KTuvoLNJXdk49Lai73i8uJAvfTRjcZdXEK/dm/XBhzHAH9Uark1iBb84M6EXb3PL4sdEga/ScdAyxquSZLr8KM2OCw7TIW2+qbhUbgWshgVKP4Z6NJwFaoVcefK81fQQG9sFYV5FDTgfKWswnY8Jeh6M8ZIdJdlw76SnSOUu7WTRh70oty2JkFKVPIs8uGrwiOC30kfDfOl3uZxu2UfL3l0+HpoDHeoxeit7mmteVGLwJlcEFrprpL8WXcSWbGkUXTOvnWCng35JiU61MyEYZ6wQtw1y/IKw2nje93TwxLGZ9ML0oojiiklWXw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

